// Mocks generated by Mockito 5.4.5 from annotations
// in poke_clean_arc_example/test/features/pokemon/presentation/Bloc/fetch_pokemon_cubit/fetch_pokemon_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:poke_clean_arc_example/poke.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonRepository_0 extends _i1.SmartFake
    implements _i2.PokemonRepository {
  _FakePokemonRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetPokemon].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemon extends _i1.Mock implements _i2.GetPokemon {
  MockGetPokemon() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePokemonRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PokemonRepository);

  @override
  _i4.Future<_i3.Either<_i2.Failure, _i2.PokemonEntity>> call({
    required _i2.PokemonParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue:
                _i4.Future<_i3.Either<_i2.Failure, _i2.PokemonEntity>>.value(
                  _FakeEither_1<_i2.Failure, _i2.PokemonEntity>(
                    this,
                    Invocation.method(#call, [], {#params: params}),
                  ),
                ),
          )
          as _i4.Future<_i3.Either<_i2.Failure, _i2.PokemonEntity>>);
}
